# SPDX-FileCopyrightText: Copyright (c) 2014-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  Exclude:
    - "assets/**/*"
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  NewCops: enable
  SuggestExtensions: false
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 15
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/ClassLength:
  Max: 360
Layout/LineLength:
  Max: 90
Metrics/MethodLength:
  Max: 35
Metrics/AbcSize:
  Max: 40
Style/MultilineBlockChain:
  Enabled: false
Metrics/BlockLength:
  Max: 50
Style/FrozenStringLiteralComment:
  Enabled: false
