docker:
  image: yegor256/rultor-image:1.9.0
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" lib/pdd/version.rb
    git add lib/pdd/version.rb
    git commit -m "version set to ${tag}"
    gem build pdd.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    LC_ALL=US-ASCII bundle exec rake
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
