---
name: rake
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  rake:
    name: rake
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
        ruby: ['2.7', '3.0']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle update
      - run: bundle exec rake
